# 注册中心地址
nacos:
  config:
    server-addr: 39.100.238.97:8848
spring:
  profiles:
    # 加密配置文件
    active: enc
  application:
    name: fehead-user-service
#  datasource:
#    username:
#    password:
#    url:
#    name:
#    type:
fehead:
  user-service:
    authenticate:
      principalParameter: password

ribbon:
  ReadTimeout: 6000000
  ConnectTimeout: 6000000
feign:
  hystrix:
    #    execution:
    #      isolation:
    #        thread:
    #          timeoutInMilliseconds: 3000
    enabled: true
  client:
    config:
      defualt:
        connectTimeout: 20000
        readTimeout: 200000